version: "3.8"
   
services:
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
    - esdata:/usr/share/elasticsearch/data
  db:
    image: postgres
    env_file:
      - var.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: var.env
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    env_file:
      - var.env
    depends_on:
      - db
      - es
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    env_file:
      - var.env
    ports:
        - "5672:5672"
        - "15672:15672"
  celery:
    build: .
    command: celery -A insurance_django_project worker -l info -B -E --loglevel=debug --concurrency=4
    volumes:
      - ./code:/code
    depends_on:
      - rabbitmq
      - db
      - mongo
  celery-beat:
    build: .
    command: celery -A insurance_django_project beat -l info 
    volumes:
      - ./code:/code
    depends_on:
      - rabbitmq
      - db
      - mongo
volumes: 
   pgdata:
   esdata:
   mongodata:
   redisdata: