version: "3.8"
   
services:
  db:
    image: postgres
    env_file:
      - var.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  migration:
    build: .
    command: python /code/manage.py migrate 
    volumes:
      - ./code:/code
    depends_on:
      - db
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    env_file:
      - var.env
    depends_on:
      - migration
      - db
volumes: 
     pgdata: