version: "3.8"
   
services:
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
    - esdata:/usr/share/elasticsearch/data
  db:
    image: postgres
    env_file:
      - var.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  migration:
    build: .
    command: python manage.py migrate 
    volumes:
      - ./code:/code
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    env_file:
      - var.env
    depends_on:
      - migration
      - db
      - es
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    env_file:
      - var.env
    ports:
        - "5672:5672"
        - "15672:15672"
  celery:
    build: .
    command: celery -A insurance_django_project worker -l info -B -E --loglevel=debug --concurrency=4
    volumes:
      - ./code:/code
    depends_on:
      - rabbitmq
  celery-beat:
    build: .
    command: celery -A insurance_django_project beat -l info 
    volumes:
      - ./code:/code
    depends_on:
      - rabbitmq
volumes: 
   pgdata:
   esdata: