version: "3.8"
   
services:
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
    - esdata:/usr/share/elasticsearch/data
  db:
    image: postgres
    env_file:
      - var.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  migration:
    build: .
    command: python manage.py migrate 
    volumes:
      - ./code:/code
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    env_file:
      - var.env
    depends_on:
      - migration
      - db
      - es
volumes: 
   pgdata:
   esdata: